import type { LAGRule, LAGToken, LAGResult } from '@/types'

export class LexerGenerator {
  private rules: LAGRule[]
  private compiledPatterns: { rule: LAGRule; regex: RegExp }[]

  constructor(rules: LAGRule[]) {
    this.rules = [...rules]
    this.compiledPatterns = this.compileRules()
  }

  private compileRules(): { rule: LAGRule; regex: RegExp }[] {
    return this.rules.map(rule => {
      try {
        const pattern = rule.pattern.startsWith('^') ? rule.pattern : `^${rule.pattern}`
        const regex = new RegExp(pattern)
        return { rule, regex }
      } catch (error) {
        throw new Error(`Invalid regex pattern for rule "${rule.name}": ${rule.pattern}`)
      }
    })
  }

  tokenize(input: string): LAGResult {
    const tokens: LAGToken[] = []
    const errors: string[] = []
    let line = 1
    let column = 1
    let pos = 0

    while (pos < input.length) {
      let matched = false
      const remainingInput = input.slice(pos)

      for (const { rule, regex } of this.compiledPatterns) {
        const match = remainingInput.match(regex)
        
        if (match && match.index === 0) {
          const value = match[0]
          
          if (rule.action === 'SKIP') {
            const newlines = (value.match(/\n/g) || []).length
            if (newlines > 0) {
              line += newlines
              const lastNewlineIndex = value.lastIndexOf('\n')
              column = value.length - lastNewlineIndex
            } else {
              column += value.length
            }
            pos += value.length
            matched = true
            break
          }

          const token: LAGToken = {
            type: rule.action || rule.name,
            value: value,
            line: line,
            column: column
          }

          tokens.push(token)

          const newlines = (value.match(/\n/g) || []).length
          if (newlines > 0) {
            line += newlines
            const lastNewlineIndex = value.lastIndexOf('\n')
            column = value.length - lastNewlineIndex
          } else {
            column += value.length
          }
          pos += value.length
          matched = true
          break
        }
      }

      if (!matched) {
        const char = input[pos]
        errors.push(`Unrecognized character "${char}" at line ${line}, column ${column}`)
        pos++
        column++
      }
    }

    return { tokens, errors }
  }

  updateRules(rules: LAGRule[]): void {
    this.rules = [...rules]
    this.compiledPatterns = this.compileRules()
  }

  getRules(): LAGRule[] {
    return [...this.rules]
  }

  addRule(rule: LAGRule): void {
    this.rules.push(rule)
    this.compiledPatterns = this.compileRules()
  }

  removeRule(index: number): void {
    if (index >= 0 && index < this.rules.length) {
      this.rules.splice(index, 1)
      this.compiledPatterns = this.compileRules()
    }
  }

  validateRule(pattern: string): { valid: boolean; error?: string } {
    try {
      new RegExp(pattern)
      return { valid: true }
    } catch (error) {
      return { valid: false, error: (error as Error).message }
    }
  }
}

export function createDefaultLexer(): LexerGenerator {
  const defaultRules: LAGRule[] = [
    { name: 'KEYWORD', pattern: 'if|else|while|for|function|return|var|let|const', action: 'KEYWORD' },
    { name: 'IDENTIFIER', pattern: '[a-zA-Z_][a-zA-Z0-9_]*', action: 'IDENTIFIER' },
    { name: 'NUMBER', pattern: '\\d+(\\.\\d+)?', action: 'NUMBER' },
    { name: 'STRING', pattern: '"[^"]*"|\'[^\']*\'', action: 'STRING' },
    { name: 'OPERATOR', pattern: '\\+|-|\\*|/|=|==|!=|<|>|<=|>=', action: 'OPERATOR' },
    { name: 'WHITESPACE', pattern: '\\s+', action: 'SKIP' },
    { name: 'COMMENT', pattern: '//.*', action: 'SKIP' }
  ]
  
  return new LexerGenerator(defaultRules)
}

export function generateLexerCode(rules: LAGRule[]): string {
  const ruleObjects = rules.map(rule => {
    const escapedPattern = rule.pattern.replace(/`/g, '\\`')
    return `    { name: '${rule.name}', pattern: \`${escapedPattern}\`, action: '${rule.action || rule.name}' }`
  }).join(',\n')

  return `// Generated Lexer
// This file was generated by Lexical Analyzer Generator (LAG)

interface Token {
  type: string
  value: string
  line: number
  column: number
}

interface LexerRule {
  name: string
  pattern: string
  action?: string
}

const rules: LexerRule[] = [
${ruleObjects}
]

class GeneratedLexer {
  private rules: LexerRule[]
  private patterns: { rule: LexerRule; regex: RegExp }[]

  constructor() {
    this.rules = rules
    this.patterns = this.compileRules()
  }

  private compileRules(): { rule: LexerRule; regex: RegExp }[] {
    return this.rules.map(rule => {
      const pattern = rule.pattern.startsWith('^') ? rule.pattern : \`^\${rule.pattern}\`
      return { rule, regex: new RegExp(pattern) }
    })
  }

  tokenize(input: string): { tokens: Token[]; errors: string[] } {
    const tokens: Token[] = []
    const errors: string[] = []
    let line = 1
    let column = 1
    let pos = 0

    while (pos < input.length) {
      let matched = false
      const remaining = input.slice(pos)

      for (const { rule, regex } of this.patterns) {
        const match = remaining.match(regex)
        
        if (match && match.index === 0) {
          const value = match[0]
          
          if (rule.action === 'SKIP') {
            const newlines = (value.match(/\n/g) || []).length
            if (newlines > 0) {
              line += newlines
              column = value.length - value.lastIndexOf('\n')
            } else {
              column += value.length
            }
            pos += value.length
            matched = true
            break
          }

          tokens.push({
            type: rule.action || rule.name,
            value: value,
            line: line,
            column: column
          })

          const newlines = (value.match(/\n/g) || []).length
          if (newlines > 0) {
            line += newlines
            column = value.length - value.lastIndexOf('\n')
          } else {
            column += value.length
          }
          pos += value.length
          matched = true
          break
        }
      }

      if (!matched) {
        errors.push(\`Unrecognized character "\${input[pos]}" at line \${line}, column \${column}\`)
        pos++
        column++
      }
    }

    return { tokens, errors }
  }
}

export default GeneratedLexer
`
}
